=== robotframework/robotframework/doc/schema/libdoc.json
{
  "title": "Libdoc",
  "description": "Libdoc JSON spec file schema.\n\nCompatible with JSON Schema Draft 2020-12.",
  "type": "object",
  "properties": {
    "specversion": {
      "$ref": "#/definitions/SpecVersion"
    },
    "name": {
      "title": "Name",
      "type": "string"
    },
    "doc": {
      "title": "Doc",
      "type": "string"
    },
    "version": {
      "title": "Version",
      "type": "string"
    },
    "generated": {
      "title": "Generated",
      "type": "string",
      "format": "date-time"
    },
    "type": {
      "$ref": "#/definitions/DocumentationType"
    },
    "scope": {
      "$ref": "#/definitions/LibraryScope"
    },
    "docFormat": {
      "$ref": "#/definitions/DocumentationFormat"
    },
    "source": {
      "title": "Source",
      "type": "string",
      "format": "path"
    },
    "lineno": {
      "title": "Lineno",
      "exclusiveMinimum": 0,
      "type": "integer"
    },
    "tags": {
      "title": "Tags",
      "description": "List of all tags used by keywords.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "inits": {
      "title": "Inits",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Keyword"
      }
    },
    "keywords": {
      "title": "Keywords",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Keyword"
      }
    },
    "typedocs": {
      "title": "Typedocs",
      "type": "array",
      "items": {
        "$ref": "#/definitions/TypeDoc"
      }
    }
  },
  "required": [
    "specversion",
    "name",
    "doc",
    "version",
    "generated",
    "type",
    "scope",
    "docFormat",
    "source",
    "lineno",
    "tags",
    "inits",
    "keywords",
    "typedocs"
  ],
  "additionalProperties": false,
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "definitions": {
    "SpecVersion": {
      "title": "SpecVersion",
      "description": "Version of the spec.",
      "enum": [
        3
      ],
      "type": "integer"
    },
    "DocumentationType": {
      "title": "DocumentationType",
      "description": "Type of the doc: LIBRARY or RESOURCE.",
      "enum": [
        "LIBRARY",
        "RESOURCE",
        "SUITE"
      ],
      "type": "string"
    },
    "LibraryScope": {
      "title": "LibraryScope",
      "description": "Library scope: GLOBAL, SUITE or TEST.",
      "enum": [
        "GLOBAL",
        "SUITE",
        "TEST"
      ],
      "type": "string"
    },
    "DocumentationFormat": {
      "title": "DocumentationFormat",
      "description": "Documentation format, typically HTML.",
      "enum": [
        "ROBOT",
        "HTML",
        "TEXT",
        "REST"
      ],
      "type": "string"
    },
    "TypeInfo": {
      "title": "TypeInfo",
      "type": "object",
      "properties": {
        "name": {
          "title": "Name",
          "type": "string"
        },
        "typedoc": {
          "title": "Typedoc",
          "description": "Map type to info in 'typedocs'.",
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "nested": {
          "title": "Nested",
          "type": "array",
          "items": {
            "$ref": "#/definitions/TypeInfo"
          }
        },
        "union": {
          "title": "Union",
          "type": "boolean"
        }
      },
      "required": [
        "name",
        "nested",
        "union"
      ],
      "additionalProperties": false
    },
    "ArgumentKind": {
      "title": "ArgumentKind",
      "description": "Argument kind: positional, named, vararg, etc.",
      "enum": [
        "POSITIONAL_ONLY",
        "POSITIONAL_ONLY_MARKER",
        "POSITIONAL_OR_NAMED",
        "VAR_POSITIONAL",
        "NAMED_ONLY_MARKER",
        "NAMED_ONLY",
        "VAR_NAMED"
      ],
      "type": "string"
    },
    "Argument": {
      "title": "Argument",
      "description": "Keyword argument.",
      "type": "object",
      "properties": {
        "name": {
          "title": "Name",
          "type": "string"
        },
        "doc": {
          "title": "Doc",
          "type": "string"
        },
        "type": {
          "title": "TypeInfo",
          "anyOf": [
            {
              "$ref": "#/definitions/TypeInfo"
            },
            {
              "type": "null"
            }
          ]
        },
        "defaultValue": {
          "title": "Defaultvalue",
          "description": "Possible default value or 'null'.",
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "kind": {
          "$ref": "#/definitions/ArgumentKind"
        },
        "required": {
          "title": "Required",
          "type": "boolean"
        },
        "repr": {
          "title": "Repr",
          "type": "string"
        }
      },
      "required": [
        "name",
        "doc",
        "kind",
        "required",
        "repr"
      ],
      "additionalProperties": false
    },
    "Keyword": {
      "title": "Keyword",
      "type": "object",
      "properties": {
        "name": {
          "title": "Name",
          "type": "string"
        },
        "doc": {
          "title": "Doc",
          "type": "string"
        },
        "shortdoc": {
          "title": "Shortdoc",
          "type": "string"
        },
        "args": {
          "title": "Args",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Argument"
          }
        },
        "returnType": {
          "title": "TypeInfo",
          "anyOf": [
            {
              "$ref": "#/definitions/TypeInfo"
            },
            {
              "type": "null"
            }
          ]
        },
        "returnDoc": {
          "title": "Returndoc",
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "tags": {
          "title": "Tags",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "private": {
          "title": "Private",
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "deprecated": {
          "title": "Deprecated",
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "source": {
          "title": "Source",
          "type": "string",
          "format": "path"
        },
        "lineno": {
          "title": "Lineno",
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "name",
        "doc",
        "shortdoc",
        "args",
        "tags",
        "source"
      ],
      "additionalProperties": false
    },
    "TypeDocType": {
      "title": "TypeDocType",
      "description": "Type of the type: Standard, Enum, TypedDict or Custom.",
      "enum": [
        "Standard",
        "Enum",
        "TypedDict",
        "Custom"
      ],
      "type": "string"
    },
    "EnumMember": {
      "title": "EnumMember",
      "type": "object",
      "properties": {
        "name": {
          "title": "Name",
          "type": "string"
        },
        "value": {
          "title": "Value",
          "type": "string"
        }
      },
      "required": [
        "name",
        "value"
      ],
      "additionalProperties": false
    },
    "TypedDictItem": {
      "title": "TypedDictItem",
      "type": "object",
      "properties": {
        "key": {
          "title": "Key",
          "type": "string"
        },
        "type": {
          "title": "Type",
          "type": "string"
        },
        "required": {
          "title": "Required",
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "key",
        "type"
      ],
      "additionalProperties": false
    },
    "TypeDoc": {
      "title": "TypeDoc",
      "type": "object",
      "properties": {
        "type": {
          "$ref": "#/definitions/TypeDocType"
        },
        "name": {
          "title": "Name",
          "type": "string"
        },
        "doc": {
          "title": "Doc",
          "type": "string"
        },
        "usages": {
          "title": "Usages",
          "description": "List of keywords using this type.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "accepts": {
          "title": "Accepts",
          "description": "List of accepted argument types.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "members": {
          "title": "Members",
          "description": "Used only with Enum type.",
          "items": {
            "$ref": "#/definitions/EnumMember"
          },
          "anyOf": [
            {
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        },
        "items": {
          "title": "Items",
          "description": "Used only with TypedDict type.",
          "items": {
            "$ref": "#/definitions/TypedDictItem"
          },
          "anyOf": [
            {
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "type",
        "name",
        "doc",
        "usages",
        "accepts"
      ],
      "additionalProperties": false
    }
  }
}

=== robotframework/robotframework/atest/testdata/libdoc/DataTypesLibrary.json
{
  "specversion": 3,
  "name": "DataTypesLibrary",
  "doc": "<p>This Library has Data Types.</p>\n<p>It has some in <code>__init__</code> and others in the <a href=\"#Keywords\" title=\"&quot;Keywords&quot; section\" class=\"name\">Keywords</a>.</p>\n<p>Custom data types include <a href=\"#type-GeoLocation\" title=\"&quot;GeoLocation&quot; type\" class=\"name\">GeoLocation</a> and <a href=\"#type-Small\" title=\"&quot;Small&quot; type\" class=\"name\">Small</a>.</p>",
  "version": "",
  "generated": "2026-07-04T12:50:42+00:00",
  "type": "LIBRARY",
  "scope": "TEST",
  "docFormat": "HTML",
  "source": "/home/peke/Devel/robotframework/atest/testdata/libdoc/DataTypesLibrary.py",
  "lineno": 91,
  "tags": [],
  "inits": [
    {
      "name": "__init__",
      "doc": "<p>This is the init Docs.</p>\n<p>It links to <a href=\"#Set%20Location\" title=\"&quot;Set Location&quot; keyword\" class=\"name\">Set Location</a> keyword and to <a href=\"#type-GeoLocation\" title=\"&quot;GeoLocation&quot; type\" class=\"name\">GeoLocation</a> data type.</p>",
      "shortdoc": "This is the init Docs.",
      "args": [
        {
          "name": "credentials",
          "doc": "",
          "type": {
            "name": "Small",
            "typedoc": "Small",
            "nested": [],
            "union": false
          },
          "defaultValue": "one",
          "kind": "POSITIONAL_OR_NAMED",
          "required": false,
          "repr": "credentials: Small = one"
        }
      ],
      "returnType": null,
      "returnDoc": "",
      "tags": [],
      "source": "/home/peke/Devel/robotframework/atest/testdata/libdoc/DataTypesLibrary.py",
      "lineno": 99
    }
  ],
  "keywords": [
    {
      "name": "Assert Something",
      "doc": "<p>This links to <a href=\"#type-AssertionOperator\" title=\"&quot;AssertionOperator&quot; type\" class=\"name\">AssertionOperator</a> .</p>\n<p>This is the next Line that links to <a href=\"#Set%20Location\" title=\"&quot;Set Location&quot; keyword\" class=\"name\">Set Location</a> .</p>",
      "shortdoc": "This links to `AssertionOperator` .",
      "args": [
        {
          "name": "value",
          "doc": "",
          "type": null,
          "defaultValue": null,
          "kind": "POSITIONAL_OR_NAMED",
          "required": true,
          "repr": "value"
        },
        {
          "name": "operator",
          "doc": "",
          "type": {
            "name": "Union",
            "typedoc": null,
            "nested": [
              {
                "name": "AssertionOperator",
                "typedoc": "AssertionOperator",
                "nested": [],
                "union": false
              },
              {
                "name": "None",
                "typedoc": "None",
                "nested": [],
                "union": false
              }
            ],
            "union": true
          },
          "defaultValue": "None",
          "kind": "POSITIONAL_OR_NAMED",
          "required": false,
          "repr": "operator: AssertionOperator | None = None"
        },
        {
          "name": "exp",
          "doc": "",
          "type": {
            "name": "str",
            "typedoc": "string",
            "nested": [],
            "union": false
          },
          "defaultValue": "something?",
          "kind": "POSITIONAL_OR_NAMED",
          "required": false,
          "repr": "exp: str = something?"
        }
      ],
      "returnType": null,
      "returnDoc": "",
      "tags": [],
      "source": "/home/peke/Devel/robotframework/atest/testdata/libdoc/DataTypesLibrary.py",
      "lineno": 109
    },
    {
      "name": "Custom",
      "doc": "",
      "shortdoc": "",
      "args": [
        {
          "name": "arg",
          "doc": "",
          "type": {
            "name": "CustomType",
            "typedoc": "CustomType",
            "nested": [],
            "union": false
          },
          "defaultValue": null,
          "kind": "POSITIONAL_OR_NAMED",
          "required": true,
          "repr": "arg: CustomType"
        },
        {
          "name": "arg2",
          "doc": "",
          "type": {
            "name": "CustomType2",
            "typedoc": "CustomType2",
            "nested": [],
            "union": false
          },
          "defaultValue": null,
          "kind": "POSITIONAL_OR_NAMED",
          "required": true,
          "repr": "arg2: CustomType2"
        },
        {
          "name": "arg3",
          "doc": "",
          "type": {
            "name": "CustomType",
            "typedoc": "CustomType",
            "nested": [],
            "union": false
          },
          "defaultValue": null,
          "kind": "POSITIONAL_OR_NAMED",
          "required": true,
          "repr": "arg3: CustomType"
        },
        {
          "name": "arg4",
          "doc": "",
          "type": {
            "name": "Unknown",
            "typedoc": null,
            "nested": [],
            "union": false
          },
          "defaultValue": null,
          "kind": "POSITIONAL_OR_NAMED",
          "required": true,
          "repr": "arg4: Unknown"
        }
      ],
      "returnType": null,
      "returnDoc": "",
      "tags": [],
      "source": "/home/peke/Devel/robotframework/atest/testdata/libdoc/DataTypesLibrary.py",
      "lineno": 142
    },
    {
      "name": "Funny Unions",
      "doc": "",
      "shortdoc": "",
      "args": [
        {
          "name": "funny",
          "doc": "",
          "type": {
            "name": "Union",
            "typedoc": null,
            "nested": [
              {
                "name": "bool",
                "typedoc": "boolean",
                "nested": [],
                "union": false
              },
              {
                "name": "int",
                "typedoc": "integer",
                "nested": [],
                "union": false
              },
              {
                "name": "float",
                "typedoc": "float",
                "nested": [],
                "union": false
              },
              {
                "name": "str",
                "typedoc": "string",
                "nested": [],
                "union": false
              },
              {
                "name": "AssertionOperator",
                "typedoc": "AssertionOperator",
                "nested": [],
                "union": false
              },
              {
                "name": "Small",
                "typedoc": "Small",
                "nested": [],
                "union": false
              },
              {
                "name": "GeoLocation",
                "typedoc": "GeoLocation",
                "nested": [],
                "union": false
              },
              {
                "name": "None",
                "typedoc": "None",
                "nested": [],
                "union": false
              }
            ],
            "union": true
          },
          "defaultValue": "equal",
          "kind": "POSITIONAL_OR_NAMED",
          "required": false,
          "repr": "funny: bool | int | float | str | AssertionOperator | Small | GeoLocation | None = equal"
        }
      ],
      "returnType": {
        "name": "Union",
        "typedoc": null,
        "nested": [
          {
            "name": "int",
            "typedoc": "integer",
            "nested": [],
            "union": false
          },
          {
            "name": "List",
            "typedoc": "list",
            "nested": [
              {
                "name": "int",
                "typedoc": "integer",
                "nested": [],
                "union": false
              }
            ],
            "union": false
          }
        ],
        "union": true
      },
      "returnDoc": "",
      "tags": [],
      "source": "/home/peke/Devel/robotframework/atest/testdata/libdoc/DataTypesLibrary.py",
      "lineno": 121
    },
    {
      "name": "Set Location",
      "doc": "",
      "shortdoc": "",
      "args": [
        {
          "name": "location",
          "doc": "",
          "type": {
            "name": "GeoLocation",
            "typedoc": "GeoLocation",
            "nested": [],
            "union": false
          },
          "defaultValue": null,
          "kind": "POSITIONAL_OR_NAMED",
          "required": true,
          "repr": "location: GeoLocation"
        }
      ],
      "returnType": {
        "name": "bool",
        "typedoc": "boolean",
        "nested": [],
        "union": false
      },
      "returnDoc": "",
      "tags": [],
      "source": "/home/peke/Devel/robotframework/atest/testdata/libdoc/DataTypesLibrary.py",
      "lineno": 106
    },
    {
      "name": "Typing Types",
      "doc": "",
      "shortdoc": "",
      "args": [
        {
          "name": "list_of_str",
          "doc": "",
          "type": {
            "name": "List",
            "typedoc": "list",
            "nested": [
              {
                "name": "str",
                "typedoc": "string",
                "nested": [],
                "union": false
              }
            ],
            "union": false
          },
          "defaultValue": null,
          "kind": "POSITIONAL_OR_NAMED",
          "required": true,
          "repr": "list_of_str: List[str]"
        },
        {
          "name": "dict_str_int",
          "doc": "",
          "type": {
            "name": "Dict",
            "typedoc": "dictionary",
            "nested": [
              {
                "name": "str",
                "typedoc": "string",
                "nested": [],
                "union": false
              },
              {
                "name": "int",
                "typedoc": "integer",
                "nested": [],
                "union": false
              }
            ],
            "union": false
          },
          "defaultValue": null,
          "kind": "POSITIONAL_OR_NAMED",
